modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="GPLv3"
issueTrackerURL="https://github.com/Affehund/${mod_id}/issues" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/${mod_id}" #optional

[[mods]] #mandatory
    modId="${mod_id}" #mandatory
    version="${version}" #mandatory
    displayName="${mod_name}" #mandatory
    authors="${mod_author}" #optional
    description='''This cloak makes you completely invisible.'''
    logoFile="logo.png" #optional
    logoBlur=false
